# Generated by Django 5.1.3 on 2024-11-09 01:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hardness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Hardness must be between 1 and 10'), django.core.validators.MaxValueValidator(10, message='Hardness must be between 1 and 10')])),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('hardness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Hardness must be between 1 and 10'), django.core.validators.MaxValueValidator(10, message='Hardness must be between 1 and 10')])),
                ('correct_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_for_question', to='mainApp.answer')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mainApp.quiz')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('quiz', 'question_number')},
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mainApp.question'),
        ),
        migrations.CreateModel(
            name='UserQuestionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='mainApp.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User question statuses',
            },
        ),
    ]
