# Generated by Django 5.1.3 on 2024-11-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
