# Generated by Django 5.1.3 on 2024-11-09 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_quiz_question_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userquestionstatus',
            options={'verbose_name_plural': 'User Question Statuses'},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_count',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_for_question', to='mainApp.answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hardness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='hardness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userquestionstatus',
            name='old_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.answer'),
        ),
        migrations.AlterField(
            model_name='userquestionstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
