# Generated by Django 5.1.3 on 2024-11-16 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_question_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_1',
            field=models.TextField(default='Option 1'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_2',
            field=models.TextField(default='Option 2'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_3',
            field=models.TextField(default='Option 3'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_4',
            field=models.TextField(default='Option 4'),
        ),
        migrations.AddField(
            model_name='userquestionstatus',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.question'),
        ),
        migrations.AddField(
            model_name='userquestionstatus',
            name='selected_answer',
            field=models.IntegerField(blank=True, choices=[(1, 'Answer 1'), (2, 'Answer 2'), (3, 'Answer 3'), (4, 'Answer 4')], null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(choices=[(1, 'Answer 1'), (2, 'Answer 2'), (3, 'Answer 3'), (4, 'Answer 4')], default=1),
        ),
        migrations.AlterField(
            model_name='userquestionstatus',
            name='old_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.answer'),
        ),
    ]
